const FETCH_USER = 'FETCH_USER';
const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';

const FETCH_USER_LIST = 'FETCH_USER_LIST';
const FETCH_USER_LIST_FULFILLED = 'FETCH_USER_LIST_FULFILLED';

export { FETCH_USER, FETCH_USER_FULFILLED, FETCH_USER_LIST, FETCH_USER_LIST_FULFILLED };
